### ISSUE TITLE
Everything slows down as you change farm layouts

### ISSUE THREAD

**Issue by Jonzo** [hpeinar/stardewplanner#28]
All functions seem snappy and responsive on initial load, but as you cycle through farm layouts, everything seems to slow down.

**Comment by hpeinar** [comment]
Indeed looks so. Will have to have a look into this.

**Comment by Ailuridaes** [comment]
I don't know if you've had a chance to look at this yet, but I spent some time digging into it and it looks like slowdown is caused by the event handlers for old boards not being unregistered on layout change. Particularly the `board.R.drag` handler - as soon as I called `undrag()` on layout change the brush dragging became much snappier. You can inspect `board.R.events` in the console and see that there's a set listed per layout loaded.

Instead of cleaning up and then initializing a new board, we can just swap in the board parts that need to be changed. I tested this locally, and it looks like your `board.loadLayout` method handles everything you need on layout change. All of the handler, helper, defs, etc setup in the board constructor is still good to go and doesn't need to be re-executed if we're using the same board.

I made a PR with that change so you can test it out yourself. If there's a reason to initialize a new board though, you can also fix the performance drop by unregistering the events from the old board on layout switch.
