### ISSUE TITLE
Consider adding a "layout" for the interior of buildings

### ISSUE THREAD

**Issue by bladeoflight16** [hpeinar/stardewplanner#38]
It would be nice to be able to plan the interiors of barns, coops, and sheds like you can the greenhouse. Layouts for each size would be helpful, as well.

**Comment by hpeinar** [comment]
I've avoided interior layouts for a reason. That would mean the planner needs to have allllllll the furniture, inside flooring options and wallpapers. Adding all these items is a massive undertaking because I'd need to convert all of them into "2D" space the planner has and that is a manual job done one by one.

If someone else would do that job, ie. generate 2D version of all the furniture, I'd happily add all the interior layouts including the house versions.

**Comment by bladeoflight16** [comment]
You're already missing decorative items that can be placed outside, like all the Rarecrows, the Stone Junimo, and the Tub o' Flowers. So I don't really see why that would be considered an absolute requirement. The planner always seemed more geared towards utility rather than pure decoration.

Furthermore, I only noted utility buildings, not housing, and Barns and Coops can't have furniture or wallpapers. (I haven't tested Sheds, but I'd be surprised if they're different.) So this isn't a barrier to those.

**Comment by hpeinar** [comment]
You are right. The missing stuff indeed doesn't justify missing the layouts themselves.

I've added all sizes of the sheds, barns and coop with respective restriction layers.
