### ISSUE TITLE
Add support for building boundaries

### ISSUE THREAD

**Issue by linkmastr001** [hpeinar/stardewplanner#7]
Buildings and Equipment have separate boundaries, so we should support each using their own sets of boundaries. For example, the Stable can't be placed in the grassy area on the top right near the house, but several Cheese Makers could.

That said, I started prototyping this in my own pull of the source, but wanted to make sure the route I was going was okay before resuming. I converted the SVG string into an array of coordinates for better readability and reuse for the building borders (because they're weird). See my pull here: https://github.com/linkmastr001/stardewplanner 

I was also thinking that the Building boundaries and Equipment boundries could be toggle on/off separately, so it might make sense to split the "Toggle grid + helpers" into a "Toggle Grid" and "Toggle Equipment Boundry" (with a line near it with the equipment boundary color) and adding a "Toggle Building Boundry" option (with a line near it with the building boundary color). Does that sound reasonable?

**Comment by hpeinar** [comment]
Different boundaries sound very reasonable. You would also need one for tilling because I'm pretty sure that one would differ from the buildings / equipment ones.

I also like your way of splitting the path into pieces so you could only re-write some of it, so, so far it looks cool. 

I'm not sure about separate toggles though, I'm not sure if there would be any need? 

Anyways I'd be happy to accept your PR once if you feel to make it into this main repo.

**Comment by hpeinar** [comment]
Closing as old issue.
